### PR TITLE
Change Language to Locale

### PR DESCRIPTION
**Pull request by elvisyjlin**
In the new schema, a tokenization request is formatted as

```
localeTag: [A locale of the sentence]
utterance: [A sentence to be tokenized]
```

For more information of sending request to the tokenization server, please refer to [`scripts/test-tokenizer.py`](https://github.com/stanford-oval/almond-tokenizer/blob/wip/lang2locale/scripts/test-tokenizer.py) and [`data/test-tokenizer-en-us.yml`](https://github.com/stanford-oval/almond-tokenizer/blob/wip/lang2locale/data/test-tokenizer-en-us.yml).

To start the server, please specify valid locales explicitly. See [`run.sh`](https://github.com/stanford-oval/almond-tokenizer/blob/wip/lang2locale/run.sh).

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
I don't like this patch, because it does not do the right fallbacks.

With this patch applied, one needs to set up different tokenizers for en-us, en-gb, en-nz, en-ca, en-au, etc.
This is not how locale tags work, according to [BCP47](https://tools.ietf.org/html/bcp47). Instead, the server should look among the supported locales, look for what the client is requesting, and do automatic fallbacks.
Also, I don't like changing the protocol from languageTag to localeTag. It will make this patch harder to deploy because we need to change all parts at once, rather than deploying almond-tokenizer first and the genie parts later.

**Comment by elvisyjlin** [comment]
Alright. I misunderstood what you mean in #19. I'm sorry.

So this is how it should work:
1. The tokenizer server supports either language or locale. If both are given, it will check if they are matched (e.g. `en` matches `en-US`).
2. Each _language_, rather than each _locale_, has a tokenizer instance in the server.
3. The server additionally creates a `zh` tokenizer with OpenCC module. It is used when the locale is `zh-tw` or `zh-hant`.

I will work on it in this way.

Do you suggest any method to map locales back to languages?

**Comment by gcampax** [comment]
Sorry, I did not see you had a question for me. I don't understand it though: why do you need to map locales to languages?
The first part before the `-` of a locale tag is the language, by the way.

**Comment by elvisyjlin** [comment]
Ah yes, you're right. That was a dumb question. I'm waiting for your confirmation of the changes I described though.
By the way, I saw you're changing the tokenizer to StanfordNLP (stanford-oval/genie-toolkit#53) and planning not to use NER anymore. I turn to have no idea whether the OpenCC plugin is necessary now.

**Comment by gcampax** [comment]
I'm planning to ditch the NER for Location, but I'm not planning to get rid of CoreNLP entirely just yet.
So yeah we'll still need this.
Anyway, I think your changes make sense although I'm a little fuzzy on the details. I'll comment on the next iteration.

**Comment by elvisyjlin** [comment]
Thank you so much for reading the code and the discussion! I'll keep doing it.

**Pull request merged**
