### PR TITLE
add zh test sentence

### PR DESCRIPTION
**Pull request by johnnychhsu**
Add sentence that fail.

### CODE REVIEW

**Comment by gcampax** [comment]
Organization is never expected to be recognized. Organizations are recognized by the parser using the pointer model.

**Comment by johnnychhsu** [comment]
I try this '当纽约时报更新时', which means 'when NYTimes update', according to corenlp.run, NYTimes can be recognized as Organization. Almond-tokenizer doesn't use this?

**Comment by gcampax** [comment]
No we don't use the organization NER.
We use the NER to preprocess the sentence and "blind" the parser to certain values. We cannot do it for organizations because we need to map new york times to a specific device and function in Thingpedia, so the parser must see the actual words "new york times", as opposed to a single opaque `ORGANIZATION_0` token.

We used to use organization NER for companies named in stock quote commands, and sport teams, cause for those you could in principle train with just `ORGANIZATION_0`, but we found it very unreliable so we got rid of that too.

NER in almond is a preprocessing step, it needs to be deterministic (or close to) and very high accuracy, otherwise you have no hope to recover because the information in the original sentence is lost. That's why we only use it for stuff that is recognizable by rules, like numbers.

**Comment by johnnychhsu** [comment]
I see. Thank you!

**Pull request closed without merging**
